name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  Security-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # CHẠY QUÉT BẢO MẬT TRỰC TIẾP TRÊN THƯ MỤC CODE (FS)
      - name: Run Trivy vulnerability scanner (Repo Scan)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs' # Quét toàn bộ file trong thư mục thay vì quét image
          scan-ref: '.'
          format: 'table'
          exit-code: '0' # Giữ nguyên 0 để dù có lỗi bảo mật lab vẫn chạy tiếp xuống bước sau
          severity: 'CRITICAL,HIGH'

  Deploy-to-AWS:
    needs: Security-Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ĐĂNG NHẬP VÀO AWS QUA OIDC ROLE
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1 # Thay đổi bằng region của bạn nếu khác

      - name: Deploy Application
        run: |
          echo "Pipeline đã quét bảo mật thành công và đang thực hiện Deploy an toàn lên EC2..."